title: Kyle Torres # your name (or website title) here
logo: "/images/Profile picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Hi, I'm Kyle! I'm a senior at Pomona College. I'm a math major with a concentration in statistics, and I'm also an economics minor. I am passionate about pursuing data science and am particularly interested in applying machine learning models.
  <br><br>
  <a href="https://www.linkedin.com/in/kyle-torres-7093521b3/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
